<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml:stylesheet type="text/xsl" href="msi.xsl" ?>
<!--
      XML Dump of Windows Installer Database
      Created with msi2xml 1.1

      (C) 2001 Daniel Gehriger (gehriger@linkcad.com)
-->
<!DOCTYPE msi [
   <!ELEMENT msi   (summary,table*)>
   <!ATTLIST msi version   CDATA #REQUIRED>
   <!ATTLIST msi xmlns:dt  CDATA #IMPLIED>
   <!ELEMENT summary       (codepage?,title?,subject?,author?,keywords?,comments?,
                            template,lastauthor?,revnumber,lastprinted?,
                            createdtm?,lastsavedtm?,pagecount,wordcount,
                            charcount?,appname?,security?)>
   <!ELEMENT codepage      (#PCDATA)>
   <!ELEMENT title         (#PCDATA)>
   <!ELEMENT subject       (#PCDATA)>
   <!ELEMENT author        (#PCDATA)>
   <!ELEMENT keywords      (#PCDATA)>
   <!ELEMENT comments      (#PCDATA)>
   <!ELEMENT template      (#PCDATA)>
   <!ELEMENT lastauthor    (#PCDATA)>
   <!ELEMENT revnumber     (#PCDATA)>
   <!ELEMENT lastprinted   (#PCDATA)>
   <!ELEMENT createdtm     (#PCDATA)>
   <!ELEMENT lastsavedtm   (#PCDATA)>
   <!ELEMENT pagecount     (#PCDATA)>
   <!ELEMENT wordcount     (#PCDATA)>
   <!ELEMENT charcount     (#PCDATA)>
   <!ELEMENT appname       (#PCDATA)>
   <!ELEMENT security      (#PCDATA)>
   <!ELEMENT table         (col+,row*)>
   <!ATTLIST table
                 name      CDATA #REQUIRED>

   <!ELEMENT col           (#PCDATA)>
   <!ATTLIST col
                 key       (yes|no) #IMPLIED
                 def       CDATA #IMPLIED>
   <!ELEMENT row (td+)>
   <!ELEMENT td            (#PCDATA)>
   <!ATTLIST td
                 href      CDATA #IMPLIED
                 dt:dt     (string|bin.base64) #IMPLIED
                 md5       CDATA #IMPLIED>
]>
<msi version="1.1" xmlns:dt="urn:schemas-microsoft-com:datatypes">
	
	<summary>
		<codepage>1252</codepage>
		<title>Installation Database</title>
		<subject>Installer Database Table Schema</subject>
		<author>Microsoft Corporation</author>
		<keywords>Installer,MSI,Database</keywords>
		<comments>Contact:  Your local administrator</comments>
		<template>;1033</template>
		<lastauthor>rich</lastauthor>
		<revnumber>{Put Package Code GUID Here}</revnumber>
		<lastprinted/>
		<createdtm>06/21/1999 00:00</createdtm>
		<lastsavedtm>12/19/2001 11:31</lastsavedtm>
		<pagecount>150</pagecount>
		<wordcount>0</wordcount>
		<charcount/>
		<appname>Windows Installer</appname>
		<security>1</security>
	</summary>
	
	<table name="ActionText">
		<col key="yes" def="s72">Action</col>
		<col def="L0">Description</col>
		<col def="L0">Template</col>
	</table>

	<table name="AdminExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AdminUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AdvtExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AdvtUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AppId">
		<col key="yes" def="s38">AppId</col>
		<col def="S255">RemoteServerName</col>
		<col def="S255">LocalService</col>
		<col def="S255">ServiceParameters</col>
		<col def="S255">DllSurrogate</col>
		<col def="I2">ActivateAtStorage</col>
		<col def="I2">RunAsInteractiveUser</col>
	</table>

	<table name="AppSearch">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="s72">Signature_</col>
	</table>

	<table name="BBControl">
		<col key="yes" def="s50">Billboard_</col>
		<col key="yes" def="s50">BBControl</col>
		<col def="s50">Type</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="L50">Text</col>
	</table>

	<table name="Billboard">
		<col key="yes" def="s50">Billboard</col>
		<col def="s38">Feature_</col>
		<col def="S50">Action</col>
		<col def="I2">Ordering</col>
	</table>

	<table name="Binary">
		<col key="yes" def="s72">Name</col>
		<col def="v0">Data</col>
	</table>

	<table name="BindImage">
		<col key="yes" def="s72">File_</col>
		<col def="S255">Path</col>
	</table>

	<table name="CCPSearch">
		<col key="yes" def="s72">Signature_</col>
	</table>

	<table name="CheckBox">
		<col key="yes" def="s72">Property</col>
		<col def="S64">Value</col>
	</table>

	<table name="Class">
		<col key="yes" def="s38">CLSID</col>
		<col key="yes" def="s32">Context</col>
		<col key="yes" def="s72">Component_</col>
		<col def="S255">ProgId_Default</col>
		<col def="L255">Description</col>
		<col def="S38">AppId_</col>
		<col def="S255">FileTypeMask</col>
		<col def="S72">Icon_</col>
		<col def="I2">IconIndex</col>
		<col def="S32">DefInprocHandler</col>
		<col def="S255">Argument</col>
		<col def="s38">Feature_</col>
		<col def="I2">Attributes</col>
	</table>

	<table name="ComboBox">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="i2">Order</col>
		<col def="s64">Value</col>
		<col def="L64">Text</col>
	</table>

	<table name="CompLocator">
		<col key="yes" def="s72">Signature_</col>
		<col def="s38">ComponentId</col>
		<col def="I2">Type</col>
	</table>

	<table name="Complus">
		<col key="yes" def="s72">Component_</col>
		<col key="yes" def="I2">ExpType</col>
	</table>

	<table name="Component">
		<col key="yes" def="s72">Component</col>
		<col def="S38">ComponentId</col>
		<col def="s72">Directory_</col>
		<col def="i2">Attributes</col>
		<col def="S255">Condition</col>
		<col def="S72">KeyPath</col>
	</table>

	<table name="Condition">
		<col key="yes" def="s38">Feature_</col>
		<col key="yes" def="i2">Level</col>
		<col def="S255">Condition</col>
	</table>

	<table name="Control">
		<col key="yes" def="s72">Dialog_</col>
		<col key="yes" def="s50">Control</col>
		<col def="s20">Type</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="S50">Property</col>
		<col def="L0">Text</col>
		<col def="S50">Control_Next</col>
		<col def="L50">Help</col>
	</table>

	<table name="ControlCondition">
		<col key="yes" def="s72">Dialog_</col>
		<col key="yes" def="s50">Control_</col>
		<col key="yes" def="s50">Action</col>
		<col key="yes" def="s255">Condition</col>
	</table>

	<table name="ControlEvent">
		<col key="yes" def="s72">Dialog_</col>
		<col key="yes" def="s50">Control_</col>
		<col key="yes" def="s50">Event</col>
		<col key="yes" def="s255">Argument</col>
		<col key="yes" def="S255">Condition</col>
		<col def="I2">Ordering</col>
	</table>

	<table name="CreateFolder">
		<col key="yes" def="s72">Directory_</col>
		<col key="yes" def="s72">Component_</col>
	</table>

	<table name="CustomAction">
		<col key="yes" def="s72">Action</col>
		<col def="i2">Type</col>
		<col def="S72">Source</col>
		<col def="S255">Target</col>
	</table>

	<table name="Dialog">
		<col key="yes" def="s72">Dialog</col>
		<col def="i2">HCentering</col>
		<col def="i2">VCentering</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="L128">Title</col>
		<col def="s50">Control_First</col>
		<col def="S50">Control_Default</col>
		<col def="S50">Control_Cancel</col>
	</table>

	<table name="Directory">
		<col key="yes" def="s72">Directory</col>
		<col def="S72">Directory_Parent</col>
		<col def="l255">DefaultDir</col>
	</table>

	<table name="DrLocator">
		<col key="yes" def="s72">Signature_</col>
		<col key="yes" def="S72">Parent</col>
		<col key="yes" def="S255">Path</col>
		<col def="I2">Depth</col>
	</table>

	<table name="DuplicateFile">
		<col key="yes" def="s72">FileKey</col>
		<col def="s72">Component_</col>
		<col def="s72">File_</col>
		<col def="L255">DestName</col>
		<col def="S72">DestFolder</col>
	</table>

	<table name="Environment">
		<col key="yes" def="s72">Environment</col>
		<col def="l255">Name</col>
		<col def="L255">Value</col>
		<col def="s72">Component_</col>
	</table>

	<table name="Error">
		<col key="yes" def="i2">Error</col>
		<col def="L0">Message</col>
	</table>

	<table name="EventMapping">
		<col key="yes" def="s72">Dialog_</col>
		<col key="yes" def="s50">Control_</col>
		<col key="yes" def="s50">Event</col>
		<col def="s50">Attribute</col>
	</table>

	<table name="Extension">
		<col key="yes" def="s255">Extension</col>
		<col key="yes" def="s72">Component_</col>
		<col def="S255">ProgId_</col>
		<col def="S64">MIME_</col>
		<col def="s38">Feature_</col>
	</table>

	<table name="Feature">
		<col key="yes" def="s38">Feature</col>
		<col def="S38">Feature_Parent</col>
		<col def="L64">Title</col>
		<col def="L255">Description</col>
		<col def="I2">Display</col>
		<col def="i2">Level</col>
		<col def="S72">Directory_</col>
		<col def="i2">Attributes</col>
	</table>

	<table name="FeatureComponents">
		<col key="yes" def="s38">Feature_</col>
		<col key="yes" def="s72">Component_</col>
	</table>

	<table name="File">
		<col key="yes" def="s72">File</col>
		<col def="s72">Component_</col>
		<col def="l255">FileName</col>
		<col def="i4">FileSize</col>
		<col def="S72">Version</col>
		<col def="S20">Language</col>
		<col def="I2">Attributes</col>
		<col def="i2">Sequence</col>
	</table>

	<table name="FileSFPCatalog">
		<col key="yes" def="s72">File_</col>
		<col key="yes" def="s255">SFPCatalog_</col>
	</table>

	<table name="Font">
		<col key="yes" def="s72">File_</col>
		<col def="S128">FontTitle</col>
	</table>

	<table name="Icon">
		<col key="yes" def="s72">Name</col>
		<col def="v0">Data</col>
	</table>

	<table name="IniFile">
		<col key="yes" def="s72">IniFile</col>
		<col def="l255">FileName</col>
		<col def="S72">DirProperty</col>
		<col def="l96">Section</col>
		<col def="l128">Key</col>
		<col def="l255">Value</col>
		<col def="i2">Action</col>
		<col def="s72">Component_</col>
	</table>

	<table name="IniLocator">
		<col key="yes" def="s72">Signature_</col>
		<col def="s255">FileName</col>
		<col def="s96">Section</col>
		<col def="s128">Key</col>
		<col def="I2">Field</col>
		<col def="I2">Type</col>
	</table>

	<table name="InstallExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="InstallUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="IsolatedComponent">
		<col key="yes" def="s72">Component_Shared</col>
		<col key="yes" def="s72">Component_Application</col>
	</table>

	<table name="LaunchCondition">
		<col key="yes" def="s255">Condition</col>
		<col def="l255">Description</col>
	</table>

	<table name="ListBox">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="i2">Order</col>
		<col def="s64">Value</col>
		<col def="L64">Text</col>
	</table>

	<table name="ListView">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="i2">Order</col>
		<col def="s64">Value</col>
		<col def="L64">Text</col>
		<col def="S72">Binary_</col>
	</table>

	<table name="LockPermissions">
		<col key="yes" def="s72">LockObject</col>
		<col key="yes" def="s32">Table</col>
		<col key="yes" def="S255">Domain</col>
		<col key="yes" def="s255">User</col>
		<col def="I4">Permission</col>
	</table>

	<table name="MIME">
		<col key="yes" def="s64">ContentType</col>
		<col def="s255">Extension_</col>
		<col def="S38">CLSID</col>
	</table>

	<table name="Media">
		<col key="yes" def="i2">DiskId</col>
		<col def="i2">LastSequence</col>
		<col def="L64">DiskPrompt</col>
		<col def="S255">Cabinet</col>
		<col def="S32">VolumeLabel</col>
		<col def="S72">Source</col>
	</table>

	<table name="MoveFile">
		<col key="yes" def="s72">FileKey</col>
		<col def="s72">Component_</col>
		<col def="L255">SourceName</col>
		<col def="L255">DestName</col>
		<col def="S72">SourceFolder</col>
		<col def="s72">DestFolder</col>
		<col def="i2">Options</col>
	</table>

	<table name="MsiAssembly">
		<col key="yes" def="s72">Component_</col>
		<col def="s38">Feature_</col>
		<col def="S72">File_Manifest</col>
		<col def="S72">File_Application</col>
		<col def="I2">Attributes</col>
	</table>

	<table name="MsiAssemblyName">
		<col key="yes" def="s72">Component_</col>
		<col key="yes" def="s255">Name</col>
		<col def="s255">Value</col>
	</table>

	<table name="MsiDigitalCertificate">
		<col key="yes" def="s72">DigitalCertificate</col>
		<col def="v0">CertData</col>
	</table>

	<table name="MsiDigitalSignature">
		<col key="yes" def="s32">Table</col>
		<col key="yes" def="s72">SignObject</col>
		<col def="s72">DigitalCertificate_</col>
		<col def="V0">Hash</col>
	</table>

	<table name="MsiFileHash">
		<col key="yes" def="s72">File_</col>
		<col def="i2">Options</col>
		<col def="i4">HashPart1</col>
		<col def="i4">HashPart2</col>
		<col def="i4">HashPart3</col>
		<col def="i4">HashPart4</col>
	</table>

	<table name="MsiPatchHeaders">
		<col key="yes" def="s38">StreamRef</col>
		<col def="v0">Header</col>
	</table>

	<table name="ODBCAttribute">
		<col key="yes" def="s72">Driver_</col>
		<col key="yes" def="s40">Attribute</col>
		<col def="L255">Value</col>
	</table>

	<table name="ODBCDataSource">
		<col key="yes" def="s72">DataSource</col>
		<col def="s72">Component_</col>
		<col def="s255">Description</col>
		<col def="s255">DriverDescription</col>
		<col def="i2">Registration</col>
	</table>

	<table name="ODBCDriver">
		<col key="yes" def="s72">Driver</col>
		<col def="s72">Component_</col>
		<col def="s255">Description</col>
		<col def="s72">File_</col>
		<col def="S72">File_Setup</col>
	</table>

	<table name="ODBCSourceAttribute">
		<col key="yes" def="s72">DataSource_</col>
		<col key="yes" def="s32">Attribute</col>
		<col def="L255">Value</col>
	</table>

	<table name="ODBCTranslator">
		<col key="yes" def="s72">Translator</col>
		<col def="s72">Component_</col>
		<col def="s255">Description</col>
		<col def="s72">File_</col>
		<col def="S72">File_Setup</col>
	</table>

	<table name="Patch">
		<col key="yes" def="s72">File_</col>
		<col key="yes" def="i2">Sequence</col>
		<col def="i4">PatchSize</col>
		<col def="i2">Attributes</col>
		<col def="V0">Header</col>
		<col def="S38">StreamRef_</col>
	</table>

	<table name="PatchPackage">
		<col key="yes" def="s38">PatchId</col>
		<col def="i2">Media_</col>
	</table>

	<table name="ProgId">
		<col key="yes" def="s255">ProgId</col>
		<col def="S255">ProgId_Parent</col>
		<col def="S38">Class_</col>
		<col def="L255">Description</col>
		<col def="S72">Icon_</col>
		<col def="I2">IconIndex</col>
	</table>

	<table name="Property">
		<col key="yes" def="s72">Property</col>
		<col def="l0">Value</col>
	</table>

	<table name="PublishComponent">
		<col key="yes" def="s38">ComponentId</col>
		<col key="yes" def="s255">Qualifier</col>
		<col key="yes" def="s72">Component_</col>
		<col def="L255">AppData</col>
		<col def="s38">Feature_</col>
	</table>

	<table name="RadioButton">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="i2">Order</col>
		<col def="s64">Value</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="L64">Text</col>
		<col def="L50">Help</col>
	</table>

	<table name="RegLocator">
		<col key="yes" def="s72">Signature_</col>
		<col def="i2">Root</col>
		<col def="s255">Key</col>
		<col def="S255">Name</col>
		<col def="I2">Type</col>
	</table>

	<table name="Registry">
		<col key="yes" def="s72">Registry</col>
		<col def="i2">Root</col>
		<col def="l255">Key</col>
		<col def="L255">Name</col>
		<col def="L0">Value</col>
		<col def="s72">Component_</col>
	</table>

	<table name="RemoveFile">
		<col key="yes" def="s72">FileKey</col>
		<col def="s72">Component_</col>
		<col def="L255">FileName</col>
		<col def="s72">DirProperty</col>
		<col def="i2">InstallMode</col>
	</table>

	<table name="RemoveIniFile">
		<col key="yes" def="s72">RemoveIniFile</col>
		<col def="l255">FileName</col>
		<col def="S72">DirProperty</col>
		<col def="l96">Section</col>
		<col def="l128">Key</col>
		<col def="L255">Value</col>
		<col def="i2">Action</col>
		<col def="s72">Component_</col>
	</table>

	<table name="RemoveRegistry">
		<col key="yes" def="s72">RemoveRegistry</col>
		<col def="i2">Root</col>
		<col def="l255">Key</col>
		<col def="L255">Name</col>
		<col def="s72">Component_</col>
	</table>

	<table name="ReserveCost">
		<col key="yes" def="s72">ReserveKey</col>
		<col def="s72">Component_</col>
		<col def="S72">ReserveFolder</col>
		<col def="i4">ReserveLocal</col>
		<col def="i4">ReserveSource</col>
	</table>

	<table name="SFPCatalog">
		<col key="yes" def="s255">SFPCatalog</col>
		<col def="v0">Catalog</col>
		<col def="S0">Dependency</col>
	</table>

	<table name="SelfReg">
		<col key="yes" def="s72">File_</col>
		<col def="I2">Cost</col>
	</table>

	<table name="ServiceControl">
		<col key="yes" def="s72">ServiceControl</col>
		<col def="l255">Name</col>
		<col def="i2">Event</col>
		<col def="L255">Arguments</col>
		<col def="I2">Wait</col>
		<col def="s72">Component_</col>
	</table>

	<table name="ServiceInstall">
		<col key="yes" def="s72">ServiceInstall</col>
		<col def="s255">Name</col>
		<col def="L255">DisplayName</col>
		<col def="i4">ServiceType</col>
		<col def="i4">StartType</col>
		<col def="i4">ErrorControl</col>
		<col def="S255">LoadOrderGroup</col>
		<col def="S255">Dependencies</col>
		<col def="S255">StartName</col>
		<col def="S255">Password</col>
		<col def="S255">Arguments</col>
		<col def="s72">Component_</col>
		<col def="L255">Description</col>
	</table>

	<table name="Shortcut">
		<col key="yes" def="s72">Shortcut</col>
		<col def="s72">Directory_</col>
		<col def="l128">Name</col>
		<col def="s72">Component_</col>
		<col def="s72">Target</col>
		<col def="S255">Arguments</col>
		<col def="L255">Description</col>
		<col def="I2">Hotkey</col>
		<col def="S72">Icon_</col>
		<col def="I2">IconIndex</col>
		<col def="I2">ShowCmd</col>
		<col def="S72">WkDir</col>
	</table>

	<table name="Signature">
		<col key="yes" def="s72">Signature</col>
		<col def="s255">FileName</col>
		<col def="S20">MinVersion</col>
		<col def="S20">MaxVersion</col>
		<col def="I4">MinSize</col>
		<col def="I4">MaxSize</col>
		<col def="I4">MinDate</col>
		<col def="I4">MaxDate</col>
		<col def="S255">Languages</col>
	</table>

	<table name="TextStyle">
		<col key="yes" def="s72">TextStyle</col>
		<col def="s32">FaceName</col>
		<col def="i2">Size</col>
		<col def="I4">Color</col>
		<col def="I2">StyleBits</col>
	</table>

	<table name="TypeLib">
		<col key="yes" def="s38">LibID</col>
		<col key="yes" def="i2">Language</col>
		<col key="yes" def="s72">Component_</col>
		<col def="I4">Version</col>
		<col def="L128">Description</col>
		<col def="S72">Directory_</col>
		<col def="s38">Feature_</col>
		<col def="I4">Cost</col>
	</table>

	<table name="UIText">
		<col key="yes" def="s72">Key</col>
		<col def="L255">Text</col>
	</table>

	<table name="Upgrade">
		<col key="yes" def="s38">UpgradeCode</col>
		<col key="yes" def="S20">VersionMin</col>
		<col key="yes" def="S20">VersionMax</col>
		<col key="yes" def="S255">Language</col>
		<col key="yes" def="i4">Attributes</col>
		<col def="S255">Remove</col>
		<col def="s72">ActionProperty</col>
	</table>

	<table name="Verb">
		<col key="yes" def="s255">Extension_</col>
		<col key="yes" def="s32">Verb</col>
		<col def="I2">Sequence</col>
		<col def="L255">Command</col>
		<col def="L255">Argument</col>
	</table>

	<table name="_Validation">
		<col key="yes" def="s32">Table</col>
		<col key="yes" def="s32">Column</col>
		<col def="s4">Nullable</col>
		<col def="I4">MinValue</col>
		<col def="I4">MaxValue</col>
		<col def="S255">KeyTable</col>
		<col def="I2">KeyColumn</col>
		<col def="S32">Category</col>
		<col def="S255">Set</col>
		<col def="S255">Description</col>
		<row>
			<td>ActionText</td>
			<td>Action</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of action to be described.</td>
		</row>
		<row>
			<td>ActionText</td>
			<td>Description</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Text</td>
			<td/>
			<td>Localized description displayed in progress dialog and log when action is executing.</td>
		</row>
		<row>
			<td>ActionText</td>
			<td>Template</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Template</td>
			<td/>
			<td>Optional localized format template used to format action data records for display during action execution.</td>
		</row>
		<row>
			<td>AdminExecuteSequence</td>
			<td>Action</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of action to invoke, either in the engine or the handler DLL.</td>
		</row>
		<row>
			<td>AdminExecuteSequence</td>
			<td>Condition</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Condition</td>
			<td/>
			<td>Optional expression which skips the action if evaluates to expFalse.If the expression syntax is invalid, the engine will terminate, returning iesBadActionData.</td>
		</row>
		<row>
			<td>AdminExecuteSequence</td>
			<td>Sequence</td>
			<td>Y</td>
			<td>-4</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Number that determines the sort order in which the actions are to be executed.  Leave blank to suppress action.</td>
		</row>
		<row>
			<td>AdminUISequence</td>
			<td>Action</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of action to invoke, either in the engine or the handler DLL.</td>
		</row>
		<row>
			<td>AdminUISequence</td>
			<td>Condition</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Condition</td>
			<td/>
			<td>Optional expression which skips the action if evaluates to expFalse.If the expression syntax is invalid, the engine will terminate, returning iesBadActionData.</td>
		</row>
		<row>
			<td>AdminUISequence</td>
			<td>Sequence</td>
			<td>Y</td>
			<td>-4</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Number that determines the sort order in which the actions are to be executed.  Leave blank to suppress action.</td>
		</row>
		<row>
			<td>AdvtExecuteSequence</td>
			<td>Action</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of action to invoke, either in the engine or the handler DLL.</td>
		</row>
		<row>
			<td>AdvtExecuteSequence</td>
			<td>Condition</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Condition</td>
			<td/>
			<td>Optional expression which skips the action if evaluates to expFalse.If the expression syntax is invalid, the engine will terminate, returning iesBadActionData.</td>
		</row>
		<row>
			<td>AdvtExecuteSequence</td>
			<td>Sequence</td>
			<td>Y</td>
			<td>-4</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Number that determines the sort order in which the actions are to be executed.  Leave blank to suppress action.</td>
		</row>
		<row>
			<td>AdvtUISequence</td>
			<td>Action</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of action to invoke, either in the engine or the handler DLL.</td>
		</row>
		<row>
			<td>AdvtUISequence</td>
			<td>Condition</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Condition</td>
			<td/>
			<td>Optional expression which skips the action if evaluates to expFalse.If the expression syntax is invalid, the engine will terminate, returning iesBadActionData.</td>
		</row>
		<row>
			<td>AdvtUISequence</td>
			<td>Sequence</td>
			<td>Y</td>
			<td>-4</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Number that determines the sort order in which the actions are to be executed.  Leave blank to suppress action.</td>
		</row>
		<row>
			<td>AppId</td>
			<td>ActivateAtStorage</td>
			<td>Y</td>
			<td>0</td>
			<td>1</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppId</td>
			<td>AppId</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Guid</td>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppId</td>
			<td>DllSurrogate</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Text</td>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppId</td>
			<td>LocalService</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Text</td>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppId</td>
			<td>RemoteServerName</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Formatted</td>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppId</td>
			<td>RunAsInteractiveUser</td>
			<td>Y</td>
			<td>0</td>
			<td>1</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppId</td>
			<td>ServiceParameters</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Text</td>
			<td/>
			<td/>
		</row>
		<row>
			<td>AppSearch</td>
			<td>Property</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>The property associated with a Signature</td>
		</row>
		<row>
			<td>AppSearch</td>
			<td>Signature_</td>
			<td>N</td>
			<td/>
			<td/>
			<td>Signature;RegLocator;IniLocator;DrLocator;CompLocator</td>
			<td>1</td>
			<td>Identifier</td>
			<td/>
			<td>The Signature_ represents a unique file signature and is also the foreign key in the Signature,  RegLocator, IniLocator, CompLocator and the DrLocator tables.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Attributes</td>
			<td>Y</td>
			<td>0</td>
			<td>2147483647</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>A 32-bit word that specifies the attribute flags to be applied to this control.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>BBControl</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of the control. This name must be unique within a billboard, but can repeat on different billboard.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Billboard_</td>
			<td>N</td>
			<td/>
			<td/>
			<td>Billboard</td>
			<td>1</td>
			<td>Identifier</td>
			<td/>
			<td>External key to the Billboard table, name of the billboard.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Height</td>
			<td>N</td>
			<td>0</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Height of the bounding rectangle of the control.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Text</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Text</td>
			<td/>
			<td>A string used to set the initial text contained within a control (if appropriate).</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Type</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>The type of the control.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Width</td>
			<td>N</td>
			<td>0</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Width of the bounding rectangle of the control.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>X</td>
			<td>N</td>
			<td>0</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Horizontal coordinate of the upper left corner of the bounding rectangle of the control.</td>
		</row>
		<row>
			<td>BBControl</td>
			<td>Y</td>
			<td>N</td>
			<td>0</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Vertical coordinate of the upper left corner of the bounding rectangle of the control.</td>
		</row>
		<row>
			<td>Billboard</td>
			<td>Action</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>The name of an action. The billboard is displayed during the progress messages received from this action.</td>
		</row>
		<row>
			<td>Billboard</td>
			<td>Billboard</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Name of the billboard.</td>
		</row>
		<row>
			<td>Billboard</td>
			<td>Feature_</td>
			<td>N</td>
			<td/>
			<td/>
			<td>Feature</td>
			<td>1</td>
			<td>Identifier</td>
			<td/>
			<td>An external key to the Feature Table. The billboard is shown only if this feature is being installed.</td>
		</row>
		<row>
			<td>Billboard</td>
			<td>Ordering</td>
			<td>Y</td>
			<td>0</td>
			<td>32767</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>A positive integer. If there is more than one billboard corresponding to an action they will be shown in the order defined by this column.</td>
		</row>
		<row>
			<td>Binary</td>
			<td>Data</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Binary</td>
			<td/>
			<td>The unformatted binary data.</td>
		</row>
		<row>
			<td>Binary</td>
			<td>Name</td>
			<td>N</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Identifier</td>
			<td/>
			<td>Unique key identifying the binary data.</td>
		</row>
		<row>
			<td>BindImage</td>
			<td>File_</td>
			<td>N</td>
			<td/>
			<td/>
			<td>File</td>
			<td>1</td>
			<td>Identifier</td>
			<td/>
			<td>The index into the File table. This must be an executable file.</td>
		</row>
		<row>
			<td>BindImage</td>
			<td>Path</td>
			<td>Y</td>
			<td/>
			<td/>
			<td/>
			<td/>
			<td>Paths</td>
			<td/>
			<td>A list of ;  delimited paths that represent the paths to be searched for the import DLLS. The list is usually a list of properties each enclosed within square brackets [] .</td>
		</row>
		<row>
			<td>CCPSearch</td>
			<td>Signature_</td>
			<td>N</td>
			<td/>
			<td/>
			<td>Signature;RegLocator;IniLocator;DrLocator;CompLocator</td>
			<td>1</td>
			<td>Identifier</td>
			<td/>
			<td>The Signature_ represents a unique file signature and is also the foreign key in the Signature,  RegLocator, IniLocator, CompLocator and the DrLocator tables.</td>
		</row>
		<row>
			<td>CheckBox</td>