<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="msi.xsl" ?>
<!--
      XML Dump of Windows Installer Database
      Created with msi2xml

      (C) 2001-2002 Daniel Gehriger (gehriger@linkcad.com)
-->
<!DOCTYPE msi [
   <!ELEMENT msi   (summary,table*)>
   <!ATTLIST msi version    CDATA #REQUIRED
                 xmlns:dt   CDATA #IMPLIED
                 msm        (yes|no) "no"
                 codepage   CDATA #IMPLIED
                 compression (MSZIP|LZX|none) "LZX">
   
   <!ELEMENT summary       (codepage?,title?,subject?,author?,keywords?,comments?,
                            template,lastauthor?,revnumber,lastprinted?,
                            createdtm?,lastsavedtm?,pagecount,wordcount,
                            charcount?,appname?,security?)>
                            
   <!ELEMENT codepage      (#PCDATA)>
   <!ELEMENT title         (#PCDATA)>
   <!ELEMENT subject       (#PCDATA)>
   <!ELEMENT author        (#PCDATA)>
   <!ELEMENT keywords      (#PCDATA)>
   <!ELEMENT comments      (#PCDATA)>
   <!ELEMENT template      (#PCDATA)>
   <!ELEMENT lastauthor    (#PCDATA)>
   <!ELEMENT revnumber     (#PCDATA)>
   <!ELEMENT lastprinted   (#PCDATA)>
   <!ELEMENT createdtm     (#PCDATA)>
   <!ELEMENT lastsavedtm   (#PCDATA)>
   <!ELEMENT pagecount     (#PCDATA)>
   <!ELEMENT wordcount     (#PCDATA)>
   <!ELEMENT charcount     (#PCDATA)>
   <!ELEMENT appname       (#PCDATA)>
   <!ELEMENT security      (#PCDATA)>                            
                                
   <!ELEMENT table         (col+,row*)>
   <!ATTLIST table
                name        CDATA #REQUIRED>

   <!ELEMENT col           (#PCDATA)>
   <!ATTLIST col
                 key       (yes|no) #IMPLIED
                 def       CDATA #IMPLIED>
                 
   <!ELEMENT row            (td+)>
   
   <!ELEMENT td             (#PCDATA)>
   <!ATTLIST td
                 href       CDATA #IMPLIED
                 dt:dt     (string|bin.base64) #IMPLIED
                 md5        CDATA #IMPLIED>
]>
<msi version="2.0" xmlns:dt="urn:schemas-microsoft-com:datatypes" codepage="1252">
	
	<summary>
		<codepage>1252</codepage>
		<title>Setup1</title>
		<subject></subject>
		<author>Pahvant Technologies, Inc.</author>
		<keywords></keywords>
		<comments></comments>
		<template>Intel;1033</template>
		<lastauthor/>
		<revnumber>{00265AFC-41E3-4059-BDC0-CAE046E2F574}</revnumber>
		<lastprinted>01/12/2004 23:19</lastprinted>
		<createdtm>06/21/1999 01:00</createdtm>
		<lastsavedtm>01/12/2004 23:19</lastsavedtm>
		<pagecount>200</pagecount>
		<wordcount>2</wordcount>
		<charcount/>
		<appname>Windows Installer</appname>
		<security>1</security>
	</summary>
	
	<table name="ActionText">
		<col key="yes" def="s72">Action</col>
		<col def="L0">Description</col>
		<col def="L0">Template</col>
	</table>

	<table name="AdminExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>CommonFilesFolder.27F5053CC80041B2AA477B9809054CFC</td>
			<td/>
			<td>1</td>
		</row>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>DIRCA_NEWRETARGETABLEPROPERTY1.27F5053CC80041B2AA477B9809054CFC</td>
			<td>NEWRETARGETABLEPROPERTY1.27F5053CC80041B2AA477B9809054CFC=""</td>
			<td>751</td>
		</row>
		<row>
			<td>DIRCA_TARGETDIR</td>
			<td>TARGETDIR=""</td>
			<td>750</td>
		</row>
		<row>
			<td>FileCost</td>
			<td/>
			<td>900</td>
		</row>
		<row>
			<td>InstallAdminPackage</td>
			<td/>
			<td>3900</td>
		</row>
		<row>
			<td>InstallFiles</td>
			<td/>
			<td>4000</td>
		</row>
		<row>
			<td>InstallFinalize</td>
			<td/>
			<td>6600</td>
		</row>
		<row>
			<td>InstallInitialize</td>
			<td/>
			<td>1500</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td/>
			<td>1400</td>
		</row>
	</table>

	<table name="AdminUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>AdminFatalErrorForm</td>
			<td/>
			<td>-3</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td/>
			<td>-1</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>Installed&lt;&gt;""</td>
			<td>999</td>
		</row>
		<row>
			<td>AdminProgressForm</td>
			<td/>
			<td>1299</td>
		</row>
		<row>
			<td>AdminResumeForm</td>
			<td>Installed="" AND RESUME</td>
			<td>998</td>
		</row>
		<row>
			<td>AdminUserExitForm</td>
			<td/>
			<td>-2</td>
		</row>
		<row>
			<td>AdminWelcomeForm</td>
			<td>Installed="" AND NOT RESUME</td>
			<td>1001</td>
		</row>
		<row>
			<td>CommonFilesFolder.27F5053CC80041B2AA477B9809054CFC</td>
			<td/>
			<td>1</td>
		</row>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>DIRCA_NEWRETARGETABLEPROPERTY1.27F5053CC80041B2AA477B9809054CFC</td>
			<td>NEWRETARGETABLEPROPERTY1.27F5053CC80041B2AA477B9809054CFC=""</td>
			<td>751</td>
		</row>
		<row>
			<td>DIRCA_TARGETDIR</td>
			<td>TARGETDIR=""</td>
			<td>750</td>
		</row>
		<row>
			<td>ExecuteAction</td>
			<td/>
			<td>1300</td>
		</row>
		<row>
			<td>FileCost</td>
			<td/>
			<td>900</td>
		</row>
	</table>

	<table name="AdvtExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>CommonFilesFolder.27F5053CC80041B2AA477B9809054CFC</td>
			<td/>
			<td>1</td>
		</row>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>CreateShortcuts</td>
			<td/>
			<td>4500</td>
		</row>
		<row>
			<td>InstallFinalize</td>
			<td/>
			<td>6600</td>
		</row>
		<row>
			<td>InstallInitialize</td>
			<td/>
			<td>1500</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td/>
			<td>1400</td>
		</row>
		<row>
			<td>MsiPublishAssemblies</td>
			<td/>
			<td>6250</td>
		</row>
		<row>
			<td>MsiUnpublishAssemblies</td>
			<td/>
			<td>1650</td>
		</row>
		<row>
			<td>PublishComponents</td>
			<td/>
			<td>6200</td>
		</row>
		<row>
			<td>PublishFeatures</td>
			<td/>
			<td>6300</td>
		</row>
		<row>
			<td>PublishProduct</td>
			<td/>
			<td>6400</td>
		</row>
		<row>
			<td>RegisterClassInfo</td>
			<td/>
			<td>4600</td>
		</row>
		<row>
			<td>RegisterExtensionInfo</td>
			<td/>
			<td>4700</td>
		</row>
		<row>
			<td>RegisterMIMEInfo</td>
			<td/>
			<td>4900</td>
		</row>
		<row>
			<td>RegisterProgIdInfo</td>
			<td/>
			<td>4800</td>
		</row>
	</table>

	<table name="AdvtUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AppId">
		<col key="yes" def="s38">AppId</col>
		<col def="S255">RemoteServerName</col>
		<col def="S255">LocalService</col>
		<col def="S255">ServiceParameters</col>
		<col def="S255">DllSurrogate</col>
		<col def="I2">ActivateAtStorage</col>
		<col def="I2">RunAsInteractiveUser</col>
	</table>

	<table name="AppSearch">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="s72">Signature_</col>
	</table>

	<table name="BBControl">
		<col key="yes" def="s50">Billboard_</col>
		<col key="yes" def="s50">BBControl</col>
		<col def="s50">Type</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="L50">Text</col>
	</table>

	<table name="Billboard">
		<col key="yes" def="s50">Billboard</col>
		<col def="s38">Feature_</col>
		<col def="S50">Action</col>
		<col def="I2">Ordering</col>
	</table>

	<table name="Binary">
		<col key="yes" def="s72">Name</col>
		<col def="v0">Data</col>
		<row>
			<td>DefBannerBitmap</td>
			<td dt:dt="bin.base64" md5="cbc1d3bd33d7d7f11158cf7574da964e">
Qk3gEwAAAAAAADYEAAAoAAAA9AEAAEYAAAABAAgAAQAAAKoPAADEDgAAxA4AAAAAAAAAAAAA
2NfoAKOgvwD5+P8AlJOVAOvm7wBINlUA//v/AD05OgBMREUABwICAA0EBAADAQEAIg4OABgK
CgAQBwcALBQUAP91dQCjS0sANhkZAGUvLwBLIyMAQB4eAP96egD0dXUAVSkpAP99fQDCX18A
gkBAAP9/fwD9f38A33BwAJNKSgCHREQAdjs7AGo1NQD/gYEA+H19APyAgADKZ2cAnVBQAP+D
gwDWbm4As1xcAKlXVwD/hIQA8n19AF0wMAD4gYEA4nZ2APyEhADqe3sA/4eHAP2GhgD0gYEA
u2NjAPmFhQDjeXkA2nR0AP+JiQD8iIgA/4uLAPiHhwD0h4cA/4+PAOiCggD+mJgAjVZWAP6l
pQAeFBQA0o+PAP61tQByVlYA8Li4AIBjYwD/yMgAr4uLAAUEBACMcnIAWUtLAP/Y2ADJq6sA
6MrKANu+vgCPfX0AuqWlAO/Y2AD/6OgAXVVVAHtycgAPDg4A//LyAF1YWADp4OAA//n5APnz
8wCNiooA//z8AFJRUQD5+PgA7u3tAIOCggDPcWwANCcmAEQvKADx6OUAUjQhAFY+MAAnFwwA
mmI8APLuzADx6ZAAbmxOAP/92gDf2D8Anp2EAKmqlwBrbGsABAoKAAIFBQAeJycAGR8fABYa
GgAlKysALTMzAEtUVAA8Q0MAQ0pKAAsMDAB8hYUAVFpaAIqSkgBzenoAERISAKewsAA3OjoA
v8fHAHh9fQClq6sA9/7+ACMkJADJzs4AkZWVAOTp6QAsLS0AOzw8ADQ1NQBTVFQARUZGAEJD
QwBvcHAAZ2hoAGNkZABbXFwA8/T0AKeoqADe+PsATWVuAMDo+QAyMzQAtrm8AP3+/wDg4eIA
tczmAPb4+wAUFx0AiIqOAGFndgChrtsAeHuLAJudqQDe4PEA8PH+AOfo9wA8PEMAlZWlAI2N
nABCQkkAvr7RAJGRoACxscEAoKCvAMrK3ADS0uEAODg5AE9PUABLS0wA+vr7ANjY2QCtra4A
oqKjAP///wD+/v4A/f39APb29gDx8fEA6urqAObm5gDk5OQA3t7eANvb2wDW1tYA0tLSAM7O
zgDJyckAxMTEAL6+vgC6uroAtra2ALGxsQCqqqoAnZ2dAJaWlgCSkpIAjY2NAIqKigCGhoYA
f39/AHt7ewB4eHgAdnZ2AHNzcwBeXl4AWVlZAFhYWABVVVUAPj4+AC8vLwAqKioAHh4eABoa
GgAVFRUACgoKAAcHBwACAgIAAQEBAAAAAABAAAAAfwLuAPe/XwAAANQAhglZAJ5kAAAAAAIA
OmSGACYCBgBNTxcAAQBKAAAA5wAYgkgAdwSGAAAAfgDKi94AnmSeAOcFVACZE4cAzh9+AP++
9b4AAP++9b4AAP++9b4AAP++9b4AAP++9b4AAP++9b4AAP++9b4AAP++9b4AAP++qr4BnwED
A4gBAwGfRL4AAP++p74ADWLStwnlfpiR5ufm2MIAQb4AAP++pL4AEVpWSlNZFR9LUWOhnwPg
55fIAEC+AAD/vqO+AAhPQz8fDiAyOgI/AAlBSl2+Y9OL4s0AD74BwQG6Lr4AAP++or4AFU88
MyYMITs6KCwZEBZBSr++zJCRygALvgAGy9R03ZfPLb4AAP++ob4AF1ZBHDobFTg6KC02KSwW
EBlDSmChl57PAAO+AVoBTwJGAApDS5eLTOuE5eS8LL4AAP++ob4ABkYZKDUiIAIzAAcyEw4V
MDwcAAMWAA4/SmiIi9JRSkEzLDIYCQLrAAdMmMrIlOLHACu+AAD/vqG+AAlDGSwyLiczOicA
A+sABBhlOiwCGQIWABBBRkISIiowMT8rC+uL3tNjAr4AA5i4wgAIvgK/Ib4AAP++ob4ACzwZ
LDUTIDotFOrnAALrABUPKjs6HC0xLCMzOSINEiAnElncvaEAA74AA9CLvAAFvgAEwMXQ0wLX
AAPVzboAHr4AAP++ob4ADEMcIzohGDsmCY/SYQLrABQNITAxJis2ODo/LCohLhgPi8PU2QK+
AATLi99iA74ABsTP2OGETAPrAAPk2JkAA74AB8nPvNDOyr8AE74AAP++ob4BRgIcAAs6KhI2
IevcvseXWQAC6wAIEicpKxQPHzICPAAoMzVAOQ+Ny2GazHuRxr7Cy9PduZKWZNiXlOPr6dfA
uwOwmNx0uZFkuxK+AAD/vqG+AA9PPBkoNy4SDubNxLvBvbcAAusAHgkUKzYuDBU2OjMsMzwb
kYe5dXkSVMfMiJeCjI7BigK+ABjBw8qT6+a92W9yu6G2s9uUdMah0r3PyMECvgADY8XBAAa+
AAD/vqG+AAxgShwZOikS65TCz8wCvgADxtmLAALrAQ4BLgIqAA8TEiAwLCMoLSJnZhQhKUEA
A0UBUQZPAVoDvgAayeLrt3NxbgKqALG0vNvex8TRluHWvs1hTpUGvgAA/76ivgFdAUYCHAAO
PCcJlWPTxsLGvr/J2OQC6wAPDRgqKyEbKzAlLC0aJjIsAAMzAjwAAz8zIwADHAAEKEFKVgK+
AA/VhLxwcW5oALWzrqnQkpUAAsEBvwHJAs0ABFdUVksGvgAA/76jvgAOWkMcOicJ183YwdZk
wbsCvgAIxdOTeesKDCICKgAIJyksPDozLCMDHAAFLC8yJBkABRYACBA/T75kmr5wAnEABG2q
tbQCsgADtJ/fAALOAAjNwc4IS1ZdUQa+AAD/vqS+AA1PLDMiWdHW1GJ035WQAALEABGhvsDK
lX3m6woPFCAqHi8lGQACHAAIIzQpIRQfHh0DHAIZAA0QLFHawqPAbnFtqrGpAAOyAAjN1dLL
dNBbUARRBr4AAP++pL4AKVpDLBR3jJPUvsXSmOHbudTDy8C+ws+VYZF5dgkSIhooIxwvNiEi
ISc5AAIcAAMZHCMAAhwACxBNmqsAq21xbquxAAOyAAWvtL10wgACyAADX1RVAAJRAVIGvgAA
/76lvgAnSiwUfcvj0svKvsfKvZeW35TMzqG+YsOhzNOWdwoqOhkoHh82Jjk+AAI8AA06Mx0l
LBwWRwCstqpiAAJuAAqxtK6vrqkBtGHJAr4AA8VXUgACVgFVBr4AAP++pb4AHlZBFJfNWdLV
mNjdvsG7y9SX3uWaz9TBvr++YoEYNwIzABM8GiEUCgwUHyZlOTAmLTMWWKuqAAIAAAerbW+k
sK4BAAKzAAS1s7nNA74B0gFQAlUBYga+AAD/vqW+ACtaQxR8yZO329i54dRh0b6hxc3Z25G5
ytbSvsjjJ0EjKR8P63qYeesJDA8VAAI2AAUgOCNfqwADAAANrLRqbGeotrW2qrW4zQADvgAE
wVxoYge+AAD/vqW+ACZWQS51gbzVkpfSzNPiknTWv6HGx8+aloTUvnQVLSYTDHZ6iMbBlgXr
AAciNSEiLb2rAAIAAAi2taZpZWqurAIAAASstbjLDr4AAP++pb4AIk8sZRgLeoO81pe9ysvQ
3eBkkbzDx77IzWPAkA8YDoR7paEDvgHRAYQE6wAHDWU5Eiu9rAACsQAIswGoZmuBqgYCqgAE
rLHdoQ6+AAD/vqS+AApgRhkzNzYUDOSXApoAFWTZz8jJmpiXuZXE1dK+zOZMeYHLugACvgAF
w83DwZgABesBGwE/AiEAEgOqs7Susq6vsrOim6O6oM/YYg6+AAD/vqS+AB5WPCwlLSwkJiEN
dnuW3NUD0s2hzNXY3eXVvnTo18kCvgAJY8vXkovZurxZAATrAAgUNSYaZLWurwKyAAuptau2
Aaebvr9k0AAPvgAA/76jvgAXYEYjLTYpIykqODkfDwt/lJbW1dTNw8YAApoAEsK64bm/wMTR
YeG419y5xpmS6gLrAAgJGzUkF0m8tAKyAAyus7UArKKnrL7PuMQPvgAA/76jvgAfVj8xGyEt
LC0fIjY+MjYiDQuRk5CW1NLPY77L5JrD3AAC4QAO2tO92NrQwr7T6esKGy8CIwARFjbZs7Kv
tLG1AJmdAZ2bYdIAEL4AAP++or4AEr9GMzgSHzMcLDcnEhQnOT02DALrA+YALI+51crc5KHF
4+thvNnd1ru+us2SDhQrPD86MxkXSbSFrrOxtQAEm6cBnNhiEL4AAP++or4ACVZBOioPNjMc
GQACLAASJh8bKy0xFHXazr3Z4Yvm5OeWAsAAGdfiZJrPu77D1mGL6RUrKWUmNikjGWUIpQEA
ArUACACqrLqiBWFjEb4AAP++or4AC08cOioOJzojHBkjAAIzABAvJCU8IHa9vpnGocu81t/N
Ar4ACZmhYrrDzdriTAAD6wADDBIPAAIMABENFCk6FxFOuK+xtgCz3LnTwwASvgAA/76hvgAJ
v0oZMzIVDCYzAAQcBCMACDor65jB0ZPPA74BwAK+AAjAwWPMlePm6AzrAA0iLygdMkIHrbmw
nuDOABS+AAD/vqG+Ab8BSgIcAAYzNgwPNjMHHAAIOjYJk8LB0soCvgANusPG0dyU5ejm45Hk
6AAL6wANCSczIxweQgiRlNzNwQAUvgAA/76ivgFPASwCHAAGOioKDx4sBhwAETomDXrGvsHF
y9KWk55/5eJhAAJ0AAPdkegAB+sC6QTrAAMPHjMAAxwBQQFWGL4AAP++or4AC11GHBkjMx8J
ITEjAAUcAAszOQ92l4h8nnjqCwAC6wAJktHImcgDl7dMAAPrAeYBWQLrAAvo5ejr6kzrIToj
GQACHAFDAV0XvgAA/76jvgALVkEcGSw0LhUtLBkAAxwAHxkoLSEMCgkKDBUTFOno4uB025e5
kVnp5pGVz9RZ6+kAAuMC6gAG5YQNJjMZAhwBKAFPF74AAP++pL4BVgFDAhwABTofGC8oAAYc
AAojMiYrKiY4MiAMCOsACea51M/Hur7A3wAC6wAK5pFZ64S5ehQwMwMcAUMXvgAA/76lvgAH
VkEsMiIqMwAIHAEsAToCPAAEPzkiCgXrAAaLknTSzGMGvgANz+br6uKG6OvjkesfOgADHAFB
F74AAP++pr4ABko0HxsxIwkcAA8jKDErDOp253+41bzJwroABb4ABsDBur5iYQLrAAPkl4sA
AusABHYKKzoDHAFBF74AAP++pr4ABUofITIsAAocAAojJCEHlta8z81jBb4AC8DCxs3U2pKV
w77WAAPrAAiTmOjrCy4tMwMcAT8XvgAA/76lvgAFWkUPGjMACRwABiMlKR4PfAe+AAjAmaHR
29/iTAPrAAVM0r7LfwAC6wAFhJbi6wwAAikABTgzGRxBABe+AAD/vqS+AAZaRi4VMigJHAAG
LDAfKROGAr4ACcDByb3VdN+Q6AAI6wAEmMFi3QPrAAth2ecNNiohLTMZQwAXvgAA/76jvgAH
WkYqDhssIwAIHAANGTNlGzAgnmO6mt7i5wAN6wAF5cu+zOUAAusAC4TTkusYKRIhNSNKABe+
AAD/vqO+AAZKOhvrJzMJHAAKGToqEzgf5MvA3QXrAecB6ArrAARkvrp0A+sACrnVfw4qIQ4m
QVYXvgAA/76jvgAHSjMb6x8zIwAHHAATGSMzIRUyGkSJvtbo6+LalpF5TAAJ6wAF48i+0ecA
AusACUzVl+sYKhQmSgAYvgAA/76jvgAHT0Ef6xUyMwAHHAAWGSw3GBUtHg2CvsuL6+HCoWS5
5oS35gfrAATVvsXhA+sACLnNhA42MEFdGL4AAP++o74ACGBKKQ/rIS8zBhwAFhksNy4MOSQM
lb7Duet/yr/L1pe4hnkH6wAFk7q+1ekAAusAB3/S2uoiQ1YAGb4AAP++pL4AA1pGIAAC6wAG
IjI6LCMcAxkAERwzIOsrOhi5Yr5k6eu8vsfTAAJ0AeEB5QJ/AegE6wAF5su+u+IAA+sABpPK
jw1Qvxm+AAD/vqW+AAtaSC4L6xQqNTwzGQADEAAXHBoOGDcfi8q+vFnr2MDIztLZl7iUi4QA
AugACOnr6ti+utrqAusABoTZkOvYwBm+AAD/vqa+ABG/UU7o6wouJzlDRkNBQz8iCQACJgAK
Wb2+y4vr48O+ywLTAAjW2HSS4eLl6ALrAAXhY77J4gAD6wJMAeYBzxq+AAD/vqi+ACnE1JNZ
6wlmWM1eXVpWRQwiOQyBYsSU61nNwGPHztPS15ePWejr6kzmzwACvgHYAeoD6wADTNe/ABq+
AAD/vqq+ACTEvd2Ui3V3lYmOvk8bFTgYesbA3evo076/yJrW15jhk5SR4lkC5wHSAr4BywGL
A+sBYQFjG74AAP++rL4AFZnDzNa4hH+U0kgvISkff8++1unr2gACvgAOw9DU0tRk2ZiP5Ezr
6mQCvgAGwNrp6+PJHL4AAP++r74ACL9jzddhi2c2AykAFw+Avsvk6+HL0NbaluGL5ed/5uO5
ldTJAAO+AATJi+i9Hb4AAP++s74ACcHMRxgnNTcTfgACwgAFt+vqWUwAAusACuiE5uSU1cnE
Y8AEvgAFYsO4ucEAHb4AAP++tL4AC15DOB8qPxpEib7gAALrAAhZ44beA83Jwwa+AAiOh4WN
luCWux6+AAD/vrS+ABBgRiwtJzI1En6ZmpJ00btjBb4ADcHEy72Cg33lDxhJzsIAH74AAP++
tb4AA1ZDIwACHgAGPytmh77BBL4ACWPHzL3cYeF4WQACDwAFFB8mRmgAIb4AAP++9b4AAP++
t74BvwJaABNdvsR+kI/leeKQk9/WvM3GY15WAAJPAANWWr8AI74AAP++9b4AAP++9b4AAP++
9b4AAP++9b4AAAAB
			</td>
		</row>
		<row>
			<td>NewFldrBtn</td>
			<td dt:dt="bin.base64" md5="326a40f5ae0f716a3818531e475678bf">
AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAwAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD/
/wD/AAAA/wD/AP//AAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiIiIiIiIAI+3t7
e3t7gAj3t7e3t7eACPt7e3t7e4AI97e3t7e3gAj7e3t7e3uACPC3t7e3t4AA8HB7e3t7gAgL
D/////+AALCwC3iIiIAACwe3gAAAAAAAgIgAAAAAAAAAAAAAAAD//wAA//8AAMAAAACAAAAA
gAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAAAAAQAAwH8AAKD/AADv/wAA
			</td>
		</row>
		<row>
			<td>UpFldrBtn</td>
			<td dt:dt="bin.base64" md5="4638b2aa55fbd0fa73bb08181895cbe7">
AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAwAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD/
/wD/AAAA/wD/AP//AAD///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIiIiIiIiIAI+3t7
e3t7gAj3t7AAALeACPt7C3t7e4AI97cHt7e3gAj7AAALe3uACPewALe3t4AI+3sLe3t7gAj/
//////+ACHt7e3iIiIAAh7e3gAAAAAAIiIgAAAAAAAAAAAAAAAD//wAA//8AAMAAAACAAAAA
gAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIAAAACAAQAAwH8AAOD/AAD//wAA
			</td>
		</row>
	</table>

	<table name="BindImage">
		<col key="yes" def="s72">File_</col>
		<col def="S255">Path</col>
	</table>

	<table name="CCPSearch">
		<col key="yes" def="s72">Signature_</col>
	</table>

	<table name="CheckBox">
		<col key="yes" def="s72">Property</col>
		<col def="S64">Value</col>
	</table>

	<table name="Class">
		<col key="yes" def="s38">CLSID</col>
		<col key="yes" def="s32">Context</col>
		<col key="yes" def="s72">Component_</col>
		<col def="S255">ProgId_Default</col>
		<col def="L255">Description</col>
		<col def="S38">AppId_</col>
		<col def="S255">FileTypeMask</col>
		<col def="S72">Icon_</col>
		<col def="I2">IconIndex</col>
		<col def="S32">DefInprocHandler</col>
		<col def="S255">Argument</col>
		<col def="s38">Feature_</col>
		<col def="I2">Attributes</col>
	</table>

	<table name="ComboBox">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="i2">Order</col>
		<col def="s64">Value</col>
		<col def="L64">Text</col>
	</table>

	<table name="CompLocator">
		<col key="yes" def="s72">Signature_</col>
		<col def="s38">ComponentId</col>
		<col def="I2">Type</col>
	</table>

	<table name="Complus">
		<col key="yes" def="s72">Component_</col>
		<col key="yes" def="I2">ExpType</col>
	</table>

	<table name="Component">
		<col key="yes" def="s72">Component</col>
		<col def="S38">ComponentId</col>
		<col def="s72">Directory_</col>
		<col def="i2">Attributes</col>
		<col def="S255">Condition</col>
		<col def="S72">KeyPath</col>
		<row>
			<td>C__003D8F659764AD90AA61B4C1EB6A6AE3</td>
			<td>{C7729BE6-17E5-CC21-5449-3B2208BD070A}</td>
			<td>_9EDC087169AF47D29AA27ED1995AC366</td>
			<td>0</td>
			<td/>
			<td>_003D8F659764AD90AA61B4C1EB6A6AE3</td>
		</row>
		<row>
			<td>C__2310D6B219C76C9FCEC2C48C889AB074</td>
			<td>{702BAEA6-AA24-1C6F-A2F8-07A16006CF63}</td>
			<td>TARGETDIR</td>
			<td>0</td>
			<td/>
			<td>_2310D6B219C76C9FCEC2C48C889AB074</td>
		</row>
		<row>
			<td>C__746C69616E6711D38E0D00C04F6837D0</td>
			<td>{AF23109E-699F-4F41-8B88-9DA098133997}</td>
			<td>TARGETDIR</td>
			<td>0</td>
			<td/>
			<td/>
		</row>
		<row>
			<td>C__76F9FBDEA8494ED8A385006F9E755ADA.27F5053CC80041B2AA477B9809054CFC</td>
			<td>{23A68467-F1D7-4061-6F4B-0F3BD7710E85}</td>
			<td>NEWRETARGETABLEPROPERTY1.27F5053CC80041B2AA477B9809054CFC</td>
			<td>0</td>
			<td/>
			<td>_76F9FBDEA8494ED8A385006F9E755ADA.27F5053CC80041B2AA477B9809054CFC</td>
		</row>
	</table>

	<table name="Condition">
		<col key="yes" def="s38">Feature_</col>
		<col key="yes" def="i2">Level</col>
		<col def="S255">Condition</col>
	</table>

	<table name="Control">
		<col key="yes" def="s72">Dialog_</col>
		<col key="yes" def="s50">Control</col>
		<col def="s20">Type</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="S50">Property</col>
		<col def="L0">Text</col>
		<col def="S50">Control_Next</col>
		<col def="L50">Help</col>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>DefBannerBitmap</td>
			<td>NextButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Confirm Installation</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>BodyText1</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer is ready to install [ProductName] on your computer.

Click "Next" to start the installation.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>NextButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Next &gt;</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminConfirmInstallForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>DefBannerBitmap</td>
			<td>CloseButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Installation Incomplete</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BodyTextInstall</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer was interrupted before [ProductName] could be removed. You need to restart the installer to try again.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>BodyTextRemove</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer was interrupted before [ProductName] could be installed. You need to restart the installer to try again.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>CloseButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Close</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFatalErrorForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>DefBannerBitmap</td>
			<td>CloseButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Installation Complete</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BodyText</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}[ProductName] has been successfully removed.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>BodyTextInstall</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>180</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}A network image of [ProductName] has been successfully created.

Click "Close" to exit.</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>CloseButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Close</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFinishedForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>DefBannerBitmap</td>
			<td>NextButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Network Location</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>Body</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>48</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}The installer will create a network image at the following location.

To create an image in this folder, click "Next". To use a different folder, enter it below or click "Browse".</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>BrowseButton</td>
			<td>PushButton</td>
			<td>282</td>
			<td>126</td>
			<td>84</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}B&amp;rowse...</td>
			<td>DiskCostButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>CancelButton</td>
			<td>PushButton</td>
			<td>156</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}Cancel</td>
			<td>PreviousButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>DiskCostButton</td>
			<td>PushButton</td>
			<td>282</td>
			<td>150</td>
			<td>84</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Disk Cost...</td>
			<td>CancelButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>FolderEdit</td>
			<td>PathEdit</td>
			<td>18</td>
			<td>126</td>
			<td>258</td>
			<td>18</td>
			<td>7</td>
			<td>TARGETDIR</td>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiPathEdit</td>
			<td>BrowseButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>FolderLabel</td>
			<td>Text</td>
			<td>18</td>
			<td>114</td>
			<td>348</td>
			<td>12</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Folder:</td>
			<td>FolderEdit</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>Line1</td>
			<td>Line</td>
			<td>0</td>
			<td>52</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>Line2</td>
			<td>Line</td>
			<td>0</td>
			<td>252</td>
			<td>375</td>
			<td>6</td>
			<td>1</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}MsiHorizontalLine</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>NextButton</td>
			<td>PushButton</td>
			<td>300</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&amp;Next &gt;</td>
			<td>FolderLabel</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminFolderForm</td>
			<td>PreviousButton</td>
			<td>PushButton</td>
			<td>228</td>
			<td>261</td>
			<td>66</td>
			<td>18</td>
			<td>3</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif13.0_0_0}&lt; &amp;Back</td>
			<td>BannerBmp</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>BannerBmp</td>
			<td>Bitmap</td>
			<td>0</td>
			<td>0</td>
			<td>375</td>
			<td>52</td>
			<td>1</td>
			<td/>
			<td>DefBannerBitmap</td>
			<td>FinishButton</td>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>BannerText</td>
			<td>Text</td>
			<td>9</td>
			<td>9</td>
			<td>306</td>
			<td>33</td>
			<td>65539</td>
			<td/>
			<td>{\VSI_MS_Sans_Serif16.0_1_0}Welcome to the [ProductName] Setup Wizard</td>
			<td/>
			<td>|</td>
		</row>
		<row>
			<td>AdminMaintenanceForm</td>
			<td>BodyText</td>
			<td>Text</td>
			<td>9</td>
			<td>63</td>
			<td>354</td>
			<td>42</td>