<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml:stylesheet type="text/xsl" href="msi.xsl" ?>
<!--
      XML Dump of Windows Installer Database
      Created with msi2xml 1.1

      (C) 2001 Daniel Gehriger (gehriger@linkcad.com)
-->
<!DOCTYPE msi [
   <!ELEMENT msi   (summary,table*)>
   <!ATTLIST msi version   CDATA #REQUIRED>
   <!ATTLIST msi xmlns:dt  CDATA #IMPLIED>
   <!ELEMENT summary       (codepage?,title?,subject?,author?,keywords?,comments?,
                            template,lastauthor?,revnumber,lastprinted?,
                            createdtm?,lastsavedtm?,pagecount,wordcount,
                            charcount?,appname?,security?)>
   <!ELEMENT codepage      (#PCDATA)>
   <!ELEMENT title         (#PCDATA)>
   <!ELEMENT subject       (#PCDATA)>
   <!ELEMENT author        (#PCDATA)>
   <!ELEMENT keywords      (#PCDATA)>
   <!ELEMENT comments      (#PCDATA)>
   <!ELEMENT template      (#PCDATA)>
   <!ELEMENT lastauthor    (#PCDATA)>
   <!ELEMENT revnumber     (#PCDATA)>
   <!ELEMENT lastprinted   (#PCDATA)>
   <!ELEMENT createdtm     (#PCDATA)>
   <!ELEMENT lastsavedtm   (#PCDATA)>
   <!ELEMENT pagecount     (#PCDATA)>
   <!ELEMENT wordcount     (#PCDATA)>
   <!ELEMENT charcount     (#PCDATA)>
   <!ELEMENT appname       (#PCDATA)>
   <!ELEMENT security      (#PCDATA)>
   <!ELEMENT table         (col+,row*)>
   <!ATTLIST table
                 name      CDATA #REQUIRED>

   <!ELEMENT col           (#PCDATA)>
   <!ATTLIST col
                 key       (yes|no) #IMPLIED
                 def       CDATA #IMPLIED>
   <!ELEMENT row (td+)>
   <!ELEMENT td            (#PCDATA)>
   <!ATTLIST td
                 href      CDATA #IMPLIED
                 dt:dt     (string|bin.base64) #IMPLIED
                 md5       CDATA #IMPLIED>
]>
<msi version="1.1" xmlns:dt="urn:schemas-microsoft-com:datatypes">
	
	<summary>
		<codepage>1252</codepage>
		<title>Installation Database</title>
		<subject>izfree</subject>
		<author>Pahvant Technologies, Inc.</author>
		<keywords>Installer,MSI,Database</keywords>
		<comments>This installation database contains the logic and data needed to install izfree.</comments>
		<template>Intel;1033</template>
		<lastauthor>rich</lastauthor>
		<revnumber>{3EF116B2-B7A6-42EC-A2CB-DA13516EBFD8}</revnumber>
		<lastprinted>12/19/2001 14:21</lastprinted>
		<createdtm>12/19/2001 14:21</createdtm>
		<lastsavedtm>12/23/2001 18:25</lastsavedtm>
		<pagecount>110</pagecount>
		<wordcount>0</wordcount>
		<charcount>0</charcount>
		<appname>MSI Database Tools</appname>
		<security>1</security>
	</summary>
	
	<table name="ActionText">
		<col key="yes" def="s72">Action</col>
		<col def="L0">Description</col>
		<col def="L0">Template</col>
		<row>
			<td>Advertise</td>
			<td>Advertising application</td>
			<td/>
		</row>
		<row>
			<td>AllocateRegistrySpace</td>
			<td>Allocating registry space</td>
			<td>Free space: [1]</td>
		</row>
		<row>
			<td>AppSearch</td>
			<td>Searching for installed applications</td>
			<td>Property: [1], Signature: [2]</td>
		</row>
		<row>
			<td>BindImage</td>
			<td>Binding executables</td>
			<td>File: [1]</td>
		</row>
		<row>
			<td>CCPSearch</td>
			<td>Searching for qualifying products</td>
			<td/>
		</row>
		<row>
			<td>CostFinalize</td>
			<td>Computing space requirements</td>
			<td/>
		</row>
		<row>
			<td>CostInitialize</td>
			<td>Computing space requirements</td>
			<td/>
		</row>
		<row>
			<td>CreateFolders</td>
			<td>Creating folders</td>
			<td>Folder: [1]</td>
		</row>
		<row>
			<td>CreateShortcuts</td>
			<td>Creating shortcuts</td>
			<td>Shortcut: [1]</td>
		</row>
		<row>
			<td>DeleteServices</td>
			<td>Deleting services</td>
			<td>Service: [1]</td>
		</row>
		<row>
			<td>DuplicateFiles</td>
			<td>Creating duplicate files</td>
			<td>File: [1],  Directory: [9],  Size: [6]</td>
		</row>
		<row>
			<td>FileCost</td>
			<td>Computing space requirements</td>
			<td/>
		</row>
		<row>
			<td>FindRelatedProducts</td>
			<td>Searching for related applications</td>
			<td>Found application: [1]</td>
		</row>
		<row>
			<td>GenerateScript</td>
			<td>Generating script operations for action:</td>
			<td>[1]</td>
		</row>
		<row>
			<td>InstallAdminPackage</td>
			<td>Copying network install files</td>
			<td>File: [1], Directory: [9], Size: [6]</td>
		</row>
		<row>
			<td>InstallFiles</td>
			<td>Copying new files</td>
			<td>File: [1],  Directory: [9],  Size: [6]</td>
		</row>
		<row>
			<td>InstallODBC</td>
			<td>Installing ODBC components</td>
			<td/>
		</row>
		<row>
			<td>InstallSFPCatalogFile</td>
			<td>Installing system catalog</td>
			<td>File: [1],  Dependencies: [2]</td>
		</row>
		<row>
			<td>InstallServices</td>
			<td>Installing new services</td>
			<td>Service: [2]</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td>Validating install</td>
			<td/>
		</row>
		<row>
			<td>LaunchConditions</td>
			<td>Evaluating launch conditions</td>
			<td/>
		</row>
		<row>
			<td>MigrateFeatureStates</td>
			<td>Migrating feature states from related applications</td>
			<td>Application: [1]</td>
		</row>
		<row>
			<td>MoveFiles</td>
			<td>Moving files</td>
			<td>File: [1],  Directory: [9],  Size: [6]</td>
		</row>
		<row>
			<td>MsiPublishAssemblies</td>
			<td>Publishing assembly information</td>
			<td>Application Context:[1], Assembly Name:[2]</td>
		</row>
		<row>
			<td>MsiUnpublishAssemblies</td>
			<td>Unpublishing assembly information</td>
			<td>Application Context:[1], Assembly Name:[2]</td>
		</row>
		<row>
			<td>PatchFiles</td>
			<td>Patching files</td>
			<td>File: [1],  Directory: [2],  Size: [3]</td>
		</row>
		<row>
			<td>ProcessComponents</td>
			<td>Updating component registration</td>
			<td/>
		</row>
		<row>
			<td>PublishComponents</td>
			<td>Publishing Qualified Components</td>
			<td>Component ID: [1], Qualifier: [2]</td>
		</row>
		<row>
			<td>PublishFeatures</td>
			<td>Publishing Product Features</td>
			<td>Feature: [1]</td>
		</row>
		<row>
			<td>PublishProduct</td>
			<td>Publishing product information</td>
			<td/>
		</row>
		<row>
			<td>RMCCPSearch</td>
			<td>Searching for qualifying products</td>
			<td/>
		</row>
		<row>
			<td>RegisterClassInfo</td>
			<td>Registering Class servers</td>
			<td>Class Id: [1]</td>
		</row>
		<row>
			<td>RegisterComPlus</td>
			<td>Registering COM+ Applications and Components</td>
			<td>AppId: [1]{{, AppType: [2], Users: [3], RSN: [4]}}</td>
		</row>
		<row>
			<td>RegisterExtensionInfo</td>
			<td>Registering extension servers</td>
			<td>Extension: [1]</td>
		</row>
		<row>
			<td>RegisterFonts</td>
			<td>Registering fonts</td>
			<td>Font: [1]</td>
		</row>
		<row>
			<td>RegisterMIMEInfo</td>
			<td>Registering MIME info</td>
			<td>MIME Content Type: [1], Extension: [2]</td>
		</row>
		<row>
			<td>RegisterProduct</td>
			<td>Registering product</td>
			<td>[1]</td>
		</row>
		<row>
			<td>RegisterProgIdInfo</td>
			<td>Registering program identifiers</td>
			<td>ProgId: [1]</td>
		</row>
		<row>
			<td>RegisterTypeLibraries</td>
			<td>Registering type libraries</td>
			<td>LibID: [1]</td>
		</row>
		<row>
			<td>RegisterUser</td>
			<td>Registering user</td>
			<td>[1]</td>
		</row>
		<row>
			<td>RemoveDuplicateFiles</td>
			<td>Removing duplicated files</td>
			<td>File: [1], Directory: [9]</td>
		</row>
		<row>
			<td>RemoveEnvironmentStrings</td>
			<td>Updating environment strings</td>
			<td>Name: [1], Value: [2], Action [3]</td>
		</row>
		<row>
			<td>RemoveExistingProducts</td>
			<td>Removing applications</td>
			<td>Application: [1], Command line: [2]</td>
		</row>
		<row>
			<td>RemoveFiles</td>
			<td>Removing files</td>
			<td>File: [1], Directory: [9]</td>
		</row>
		<row>
			<td>RemoveFolders</td>
			<td>Removing folders</td>
			<td>Folder: [1]</td>
		</row>
		<row>
			<td>RemoveIniValues</td>
			<td>Removing INI files entries</td>
			<td>File: [1],  Section: [2],  Key: [3], Value: [4]</td>
		</row>
		<row>
			<td>RemoveODBC</td>
			<td>Removing ODBC components</td>
			<td/>
		</row>
		<row>
			<td>RemoveRegistryValues</td>
			<td>Removing system registry values</td>
			<td>Key: [1], Name: [2]</td>
		</row>
		<row>
			<td>RemoveShortcuts</td>
			<td>Removing shortcuts</td>
			<td>Shortcut: [1]</td>
		</row>
		<row>
			<td>Rollback</td>
			<td>Rolling back action:</td>
			<td>[1]</td>
		</row>
		<row>
			<td>RollbackCleanup</td>
			<td>Removing backup files</td>
			<td>File: [1]</td>
		</row>
		<row>
			<td>SelfRegModules</td>
			<td>Registering modules</td>
			<td>File: [1], Folder: [2]</td>
		</row>
		<row>
			<td>SelfUnregModules</td>
			<td>Unregistering modules</td>
			<td>File: [1], Folder: [2]</td>
		</row>
		<row>
			<td>SetODBCFolders</td>
			<td>Initializing ODBC directories</td>
			<td/>
		</row>
		<row>
			<td>StartServices</td>
			<td>Starting services</td>
			<td>Service: [1]</td>
		</row>
		<row>
			<td>StopServices</td>
			<td>Stopping services</td>
			<td>Service: [1]</td>
		</row>
		<row>
			<td>UnmoveFiles</td>
			<td>Removing moved files</td>
			<td>File: [1], Directory: [9]</td>
		</row>
		<row>
			<td>UnpublishComponents</td>
			<td>Unpublishing Qualified Components</td>
			<td>Component ID: [1], Qualifier: [2]</td>
		</row>
		<row>
			<td>UnpublishFeatures</td>
			<td>Unpublishing Product Features</td>
			<td>Feature: [1]</td>
		</row>
		<row>
			<td>UnpublishProduct</td>
			<td>Unpublishing product information</td>
			<td/>
		</row>
		<row>
			<td>UnregisterClassInfo</td>
			<td>Unregister Class servers</td>
			<td>Class Id: [1]</td>
		</row>
		<row>
			<td>UnregisterComPlus</td>
			<td>Unregistering COM+ Applications and Components</td>
			<td>AppId: [1]{{, AppType: [2]}}</td>
		</row>
		<row>
			<td>UnregisterExtensionInfo</td>
			<td>Unregistering extension servers</td>
			<td>Extension: [1]</td>
		</row>
		<row>
			<td>UnregisterFonts</td>
			<td>Unregistering fonts</td>
			<td>Font: [1]</td>
		</row>
		<row>
			<td>UnregisterMIMEInfo</td>
			<td>Unregistering MIME info</td>
			<td>MIME Content Type: [1], Extension: [2]</td>
		</row>
		<row>
			<td>UnregisterProgIdInfo</td>
			<td>Unregistering program identifiers</td>
			<td>ProgId: [1]</td>
		</row>
		<row>
			<td>UnregisterTypeLibraries</td>
			<td>Unregistering type libraries</td>
			<td>LibID: [1]</td>
		</row>
		<row>
			<td>WriteEnvironmentStrings</td>
			<td>Updating environment strings</td>
			<td>Name: [1], Value: [2], Action [3]</td>
		</row>
		<row>
			<td>WriteIniValues</td>
			<td>Writing INI files values</td>
			<td>File: [1],  Section: [2],  Key: [3], Value: [4]</td>
		</row>
		<row>
			<td>WriteRegistryValues</td>
			<td>Writing system registry values</td>
			<td>Key: [1], Name: [2], Value: [3]</td>
		</row>
	</table>

	<table name="AdminExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>FileCost</td>
			<td/>
			<td>900</td>
		</row>
		<row>
			<td>InstallAdminPackage</td>
			<td/>
			<td>3900</td>
		</row>
		<row>
			<td>InstallFiles</td>
			<td/>
			<td>4000</td>
		</row>
		<row>
			<td>InstallFinalize</td>
			<td/>
			<td>6600</td>
		</row>
		<row>
			<td>InstallInitialize</td>
			<td/>
			<td>1500</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td/>
			<td>1400</td>
		</row>
	</table>

	<table name="AdminUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>AdminWelcomeDlg</td>
			<td/>
			<td>1230</td>
		</row>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>ExecuteAction</td>
			<td/>
			<td>1300</td>
		</row>
		<row>
			<td>ExitDialog</td>
			<td/>
			<td>-1</td>
		</row>
		<row>
			<td>FatalError</td>
			<td/>
			<td>-3</td>
		</row>
		<row>
			<td>FileCost</td>
			<td/>
			<td>900</td>
		</row>
		<row>
			<td>PrepareDlg</td>
			<td/>
			<td>140</td>
		</row>
		<row>
			<td>ProgressDlg</td>
			<td/>
			<td>1280</td>
		</row>
		<row>
			<td>UserExit</td>
			<td/>
			<td>-2</td>
		</row>
	</table>

	<table name="AdvtExecuteSequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
		<row>
			<td>CostFinalize</td>
			<td/>
			<td>1000</td>
		</row>
		<row>
			<td>CostInitialize</td>
			<td/>
			<td>800</td>
		</row>
		<row>
			<td>CreateShortcuts</td>
			<td/>
			<td>4500</td>
		</row>
		<row>
			<td>InstallFinalize</td>
			<td/>
			<td>6600</td>
		</row>
		<row>
			<td>InstallInitialize</td>
			<td/>
			<td>1500</td>
		</row>
		<row>
			<td>InstallValidate</td>
			<td/>
			<td>1400</td>
		</row>
		<row>
			<td>MsiPublishAssemblies</td>
			<td/>
			<td>6250</td>
		</row>
		<row>
			<td>PublishComponents</td>
			<td/>
			<td>6200</td>
		</row>
		<row>
			<td>PublishFeatures</td>
			<td/>
			<td>6300</td>
		</row>
		<row>
			<td>PublishProduct</td>
			<td/>
			<td>6400</td>
		</row>
		<row>
			<td>RegisterClassInfo</td>
			<td/>
			<td>4600</td>
		</row>
		<row>
			<td>RegisterExtensionInfo</td>
			<td/>
			<td>4700</td>
		</row>
		<row>
			<td>RegisterMIMEInfo</td>
			<td/>
			<td>4900</td>
		</row>
		<row>
			<td>RegisterProgIdInfo</td>
			<td/>
			<td>4800</td>
		</row>
	</table>

	<table name="AdvtUISequence">
		<col key="yes" def="s72">Action</col>
		<col def="S255">Condition</col>
		<col def="I2">Sequence</col>
	</table>

	<table name="AppId">
		<col key="yes" def="s38">AppId</col>
		<col def="S255">RemoteServerName</col>
		<col def="S255">LocalService</col>
		<col def="S255">ServiceParameters</col>
		<col def="S255">DllSurrogate</col>
		<col def="I2">ActivateAtStorage</col>
		<col def="I2">RunAsInteractiveUser</col>
	</table>

	<table name="AppSearch">
		<col key="yes" def="s72">Property</col>
		<col key="yes" def="s72">Signature_</col>
		<row>
			<td>IE_VERSION</td>
			<td>rtsigIEVersion</td>
		</row>
		<row>
			<td>IE_VERSION</td>
			<td>rtsigIEVersion3</td>
		</row>
	</table>

	<table name="BBControl">
		<col key="yes" def="s50">Billboard_</col>
		<col key="yes" def="s50">BBControl</col>
		<col def="s50">Type</col>
		<col def="i2">X</col>
		<col def="i2">Y</col>
		<col def="i2">Width</col>
		<col def="i2">Height</col>
		<col def="I4">Attributes</col>
		<col def="L50">Text</col>
	</table>

	<table name="Billboard">
		<col key="yes" def="s50">Billboard</col>
		<col def="s38">Feature_</col>
		<col def="S50">Action</col>
		<col def="I2">Ordering</col>
	</table>

	<table name="Binary">
		<col key="yes" def="s72">Name</col>
		<col def="v0">Data</col>
		<row>
			<td>New</td>
			<td dt:dt="bin.base64" md5="c23cbf002d82192481b61ed7ec0890f4">
AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD/
/wD/AAAA/wD/AP//AAD///8AAAAAAAAAAAAAAAAAAAAAAAC7u7u7sAAAALu7u7uwAAAAu7u7
u7AAAAC7u7u7sAAAALu7u7uwAAAAu7u7u7AAAAAAAAAAAAAAAAu7sAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAgA8AAIAPAACADwAA
gA8AAIANAACACwAAgAcAAIAaAADA1wAA4asAAP99AAD/7wAA//8AAP/vAAD//wAA
			</td>
		</row>
		<row>
			<td>Up</td>
			<td dt:dt="bin.base64" md5="83730ac00391fb0f02f56fe2e4207a10">
AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAACAAACAAAAAgIAAgAAAAIAAgACAgAAAwMDAAICAgAAAAP8AAP8AAAD/
/wD/AAAA/wD/AP//AAD///8AAAAAAAAAAAAAAAAAAAAAAAC7u7u7u7uwALu7u7u7u7AAu7sA
AAC7sAC7uwu7u7uwALu7C7u7u7AAuwAAC7u7sAC7sAC7u7uwALu7C7u7u7AAu7u7u7u7sAAA
AAAAAAAAAAu7uwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAgAAAAIAAAACAAAAA
gAAAAIAAAACAAAAAgAAAAIAAAACAAAAAgAAAAIABAADAfwAA4P8AAP//AAD//wAA
			</td>
		</row>
		<row>
			<td>bannrbmp</td>
			<td dt:dt="bin.base64" md5="66fa78be0ee19183677cfe5ae0f61392">
Qk1acQEAAAAAADYAAAAoAAAA9AEAAD8AAAABABgAAAAAACRxAQDEDgAAxA4AAAAAAAAAAAAA
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////